# Generated by Django 2.0.1 on 2018-01-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeedUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Feeds',
        ),
        migrations.AddField(
            model_name='feeddetail',
            name='feed_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.FeedUrl'),
        ),
    ]
