# Generated by Django 2.0.1 on 2018-01-29 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20180129_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeddetail',
            name='story_url',
            field=models.URLField(default='https://www.google.ca/'),
        ),
        migrations.AddField(
            model_name='feeddetail',
            name='timestamp',
            field=models.TimeField(default=datetime.time(20, 56, 6, 846442)),
        ),
        migrations.AddField(
            model_name='feeddetail',
            name='title',
            field=models.CharField(default='asd', max_length=1000),
        ),
    ]
