# Generated by Django 2.0.1 on 2018-02-14 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20180129_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeddetail',
            name='category',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='feeddetail',
            name='timestamp',
            field=models.TimeField(default=datetime.time(23, 2, 6, 68625)),
        ),
    ]
